booking:
  post:
    tags:
    - Booking
    summary: Create booking record
    consumes: application/json
    properties: ''
    requestBody:
      content:
        application/json:
          schema:
            $ref: 'swagger-schemas.yaml#/booking'
    responses:
      '200':
        description: 'Created booking'
        content:
          application/json:
            schema:
              $ref: 'swagger-schemas.yaml#/booking'
      '400':
        description: 'Incorrect data'
  get:
    tags:
    - Booking
    summary: Get all booking records
    responses:
      '200':
        description: 'Bookings'
        content:
          application/json:
            schema: 
              properties:
                results:
                  type: array
                  items: 
                    $ref: 'swagger-schemas.yaml#/booking'
booking_by_id:
  get:
    tags:
    - Booking
    summary: Get booking by id
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID of the booking
    responses:
      '200':
        description: 'Booking record withmatched id'
        content:
          application/json:
            schema:
              $ref: 'swagger-schemas.yaml#/booking'
      '404':
        description: 'Not found'
        content:
          application/json:
            schema:
              properties:
                message:
                  type: string
  delete:  
    tags:
      - Booking
    summary: Delete booking   
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID of the booking
    responses:
      '200':
        description: 'Deleted booking data'
        content:
          application/json:
            schema:
              $ref: 'swagger-schemas.yaml#/booking'
  put:  
    tags:
      - Booking
    summary: Update booking   
    requestBody:
      content:
        application/json:
          schema:
            $ref: 'swagger-schemas.yaml#/booking'
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID of the booking
    responses:
      '200':
        description: 'updated booking data'
        content:
          application/json:
            schema:
              $ref: 'swagger-schemas.yaml#/booking'                           
