booking-room:
    post:
        tags:
            - Booking room
        summary: Connect booking to the room with specific id
        consumes: application/json
        properties: ''
        requestBody:
            content:
                application/json:
                    schema:
                        $ref: 'swagger-schemas.yaml#/booking-rooms'
        responses:
            '200':
                description: 'Room booking'
                content:
                    application/json:
                        schema:
                            $ref: 'swagger-schemas.yaml#/booking-rooms'
            '400':
                description: 'Incorrect data'
    get:
        tags:
            - Booking room
        summary: Get all booking room records
        responses:
            '200':
                description: 'Booking rooms'
                content:
                    application/json:
                        schema:
                            properties:
                                results:
                                    type: array
                                    items:
                                        $ref: 'swagger-schemas.yaml#/booking-rooms'
booking-room-by-id:
    get:
        tags:
            - Booking room
        summary: Get booking room record by id
        parameters:
            - in: path
              name: id
              schema:
                  type: integer
              required: true
              description: ID of the room booking
        responses:
            '200':
                description: 'Room booking record with matched id'
                content:
                    application/json:
                        schema:
                            $ref: 'swagger-schemas.yaml#/booking-rooms'
            '404':
                description: 'Not found'
                content:
                    application/json:
                        schema:
                            properties:
                                message:
                                    type: string
    delete:
        tags:
            - Booking room
        summary: Delete room booking
        parameters:
            - in: path
              name: id
              schema:
                  type: integer
              required: true
              description: ID of the room booking
        responses:
            '200':
                description: 'Deleted room booking data'
                content:
                    application/json:
                        schema:
                            $ref: 'swagger-schemas.yaml#/booking-rooms'
    put:
        tags:
            - Booking room
        summary: Update room booking
        requestBody:
            content:
                application/json:
                    schema:
                        $ref: 'swagger-schemas.yaml#/booking-rooms'
        parameters:
            - in: path
              name: id
              schema:
                  type: integer
              required: true
              description: ID of the room booking
        responses:
            '200':
                description: 'updated room booking data'
                content:
                    application/json:
                        schema:
                            $ref: 'swagger-schemas.yaml#/booking-rooms'
