openapi: 3.0.0

info:
  version: 1.0.0
  title: Booking API

paths:
 # Test
  "/api/v1/test":
    get:
      summary: Testing route
      tags:
      - Test route
      parameters: []
      responses:
        '200':
          description: OK
 # Authentication
  "/api/v1/auth/login":
    $ref: 'swagger-auth.yaml#/login'
  "/api/v1/auth/register":
    $ref: 'swagger-auth.yaml#/register'
  "/api/v1/auth/refresh-token":
    $ref: 'swagger-auth.yaml#/token'
 # Properties
  "/api/v1/properties":
    $ref: 'swagger-properties.yaml#/properties'
  "/api/v1/properties/{id}":
    $ref: 'swagger-properties.yaml#/properties_by_id'
 # Booking
  "/api/v1/booking":
    $ref: 'swagger-booking.yaml#/booking'
  "/api/v1/booking/{id}":
    $ref: 'swagger-booking.yaml#/booking_by_id'          
 # Booking rooms
  "/api/v1/booking-room":
    $ref: 'swagger-booking-rooms.yaml#/booking-room'
  "/api/v1/booking-room/{id}":
    $ref: 'swagger-booking-rooms.yaml#/booking-room-by-id'
 # cities
  "/api/v1/cities":
    $ref: 'swagger-cities.yaml#/cities'
 # reviews
  "/api/v1/review":
    $ref: 'swagger-reviews.yaml#/reviews'
  "/api/v1/review/{id}":
    $ref: 'swagger-reviews.yaml#/reviews-by-id'            